"""empty message

Revision ID: 43cfde65fe31
Revises: ad62cb2c87ab
Create Date: 2023-10-31 07:22:19.205160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43cfde65fe31'
down_revision = 'ad62cb2c87ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penjual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('stok')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penjual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stok', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
