"""empty message

Revision ID: 8343bdaaca15
Revises: 43cfde65fe31
Create Date: 2023-10-31 08:02:01.812641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8343bdaaca15'
down_revision = '43cfde65fe31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penjual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo', sa.Integer(), nullable=True))
        batch_op.alter_column('alamat',
               existing_type=mysql.VARCHAR(length=355),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penjual', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=mysql.VARCHAR(length=355),
               nullable=True)
        batch_op.drop_column('saldo')

    # ### end Alembic commands ###
