"""empty message

Revision ID: 836745e66535
Revises: d38b4f2a8da6
Create Date: 2023-10-30 17:42:00.622297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '836745e66535'
down_revision = 'd38b4f2a8da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
