"""empty message

Revision ID: ad62cb2c87ab
Revises: 7008453a1caa
Create Date: 2023-10-31 06:42:24.900754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad62cb2c87ab'
down_revision = '7008453a1caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penjual',
    sa.Column('id_penjual', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_penjual', sa.String(length=155), nullable=False),
    sa.Column('alamat', sa.String(length=355), nullable=True),
    sa.Column('telp', sa.Integer(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_penjual')
    )
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_penjual', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'penjual', ['id_penjual'], ['id_penjual'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_penjual')

    op.drop_table('penjual')
    # ### end Alembic commands ###
